---
title: "Using ChatGPT for Title and Abstract Screening in Systematic Reviews"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using ChatGPT for Title and Abstract Screening in Systematic Reviews}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

[INSERT NOTE ABOUT RETROSPECTIVE CAVEAT]

Loading relevant packages. 
```{r setup, message=FALSE, warning=FALSE}
library(AIscreenR)
library(revtools)
library(tibble)
library(dplyr)
library(purrr)
library(usethis)
```

## Loading relevant ris file data for screening

## Handling the API key with `AIscreenR`

### Temporary solution

### Pemanent solution

## Retrieve rate limit information 

```{r, eval = FALSE}
# Rate limits across one model
rate_limits <- rate_limits_per_minute(model = "gpt-3.5-turbo-0613")
rate_limits

# Rate limit overview across multiple models
models <- c("gpt-3.5-turbo-0613", "gpt-3.5-turbo-16k-0613", "gpt-4") # Add further models if necessary

models_rate_limits <- 
  map(models, ~ rate_limits_per_minute(model = .x)) |> 
  list_rbind()

models_rate_limits
```

## Approximate price of screening

Example of how to enter a prompt. Can also be done in word.

```{r}
prompt <- "Evaluate the following study based on the selection criteria
for a systematic review on the effects of family-based interventions on drug 
abuse reduction for young people in treatment for non-opioid drug use.
A family-based intervention (FFT) is equivalent to a behavior focused
family therapy, where young people’s drug use is understood in relation to 
family behavior problems. Family-based interventions also includes manual-based 
family therapies as it targets young people and their families as a system 
throughout treatment, and thereby recognizes the important role of the family 
system in the development and treatment of young people’s drug use problems. 
FFT was developed in the late 1980s on request from the US National Institute on
Drug Abuse (NIDA). The development of FFT was initially heavily inspired by the 
alcohol abuse program Community Reinforcement Approach (CRA), which was aimed 
at restructuring the environment to reinforce non-alcohol associated activities. 
FFT developed to have more emphasis on contingency contracting, impulse control 
strategies specific to drug use, and increased emphasis on involvement of family 
members in treatment. FFT is designed to accommodate diverse populations of 
youths with a variety of behavioral, cultural and individual preferences. 
FFT has evolved for use in severe behavioral disturbances known to co-exist with
substance use and dependence, and the core interventions have been enhanced to 
address several mental health related problems commonly occurring
as comorbid conditions in drug use treatment participant.  For each study,
I would like you to assess:  1) Is the study about a family-based intervention,
such as Functional Family Therapy, Multidimensional Family Therapy, or
Behavioral Family Therapy? (Outpatient manual-based interventions of any
duration delivered to young people and their families). If not, exclude study.
2) Are the participants in outpatient drug treatment primarily
for non-opioid drug use? 3) Are the participants within age 11–21?"
```

Approximate price of screening

```{r}
app_obj <- 
  approximate_price_gpt(
    data = FFT_dat, 
    prompt = prompt,
    studyid = studyid, # indicate the variable with the studyid in the data
    title = title, # indicate the variable with the titles in the data
    abstract = abstract, # indicate the variable with the abstracts in the data
    model = c("gpt-3.5-turbo-0613"),
    rep = 10 
  )

app_obj

app_obj$price_dollar
app_obj$price_data

```


